#!/bin/bash

SETCOLOR_SUCCESS="echo -en \\033[0;32m"
SETCOLOR_NORMAL="echo -en \\033[0;39m"

declare TTL="WEB"

declare pw=$("pwd")
declare project=""
if [[ $pw =~ (.*\/)(.*) ]]; then
    project=${BASH_REMATCH[2]}
fi

declare src="$pw/src/$project"
declare bin="$pw/bin"

function check_dirs() {
    local -n ari=$1

    # creates folders if not exists
    for page in "${ari[@]}"
    do
        IFS=";" read -r -a arr <<< "${page}"

        declare fde="${arr[1]}"
        declare dirna="$(dirname "${fde}")"

        if [ ! -e $dirna ]; then
            echo "creating $dirna"
            mkdir -p $dirna
        fi
    done
}

function copy_folder() {
    local -n ari=$1

    for page in "${ari[@]}"
    do
        IFS=";" read -r -a arr <<< "${page}"

        declare fsr="${arr[0]}"
        declare fde="${arr[1]}"

        if [ -e $fde ]; then
            continue
        fi

        declare out=$(cp -r -v "$fsr" "$fde")
        if [[ ! -z $out ]]; then
            echo "copy dir $fsr"
        fi
    done
}

function copira() {
    local -n acp=$1

    declare some=""

    for page in "${acp[@]}"
    do
        IFS=";" read -r -a arr <<< "${page}"

        declare fos="${arr[0]}"
        declare fot="${arr[1]}"

        declare out=$(cp -u -v "$fos" "$fot")

        if [[ ! -z $out ]]; then
            declare bn=$(basename "$fos")

            if [[ ! -z $some ]]; then
                some="${some}"$'\n'
            fi

            some="${some}${bn}"
        fi
    done

    if [[ ! -z $some ]]; then
        printf "%-20s%s\n" "$some"
    fi
}

FF=(
    "$src/static/js/libs;$bin/static/js/libs/"
    "$src/static/images;$bin/static/images/"
)

PP=(
    "$src/config.json;$bin/config.json"
    "$src/templates/site/layout_emp.html;$bin/templates/site/layout_emp.html"
    "$src/templates/site/layout_ajax.html;$bin/templates/site/layout_ajax.html"
    "$src/static/css/reset.css;$bin/static/css/reset.css"
# wschat_page
    "$src/templates/site/wschat/ix.html;$bin/templates/site/wschat/ix.html"
    "$src/templates/site/wschat/st_meet.html;$bin/templates/site/wschat/st_meet.html"
    "$src/templates/site/wschat/sta.html;$bin/templates/site/wschat/sta.html"
    "$src/templates/site/wschat/camic.html;$bin/templates/site/wschat/camic.html"
    "$src/templates/site/wschat/virt.html;$bin/templates/site/wschat/virt.html"
# wschat_page css
    "$src/static/css/pages/wschat/ix.css;$bin/static/css/wschat/ix.css"
    "$src/static/css/pages/wschat/room.css;$bin/static/css/wschat/room.css"
# wschat_page js
    "$src/static/js/components/wschat/ix.js;$bin/static/js/wschat/ix.js"
    "$src/static/js/components/wschat/wschat.js;$bin/static/js/wschat/wschat.js"
    "$src/static/js/components/wschat/resie.js;$bin/static/js/wschat/resie.js"
    "$src/static/js/components/wschat/talkerhandler.js;$bin/static/js/wschat/talkerhandler.js"
    "$src/static/js/components/wschat/vmeter.js;$bin/static/js/wschat/vmeter.js"
    "$src/static/js/components/wschat/virt.js;$bin/static/js/wschat/virt.js"
    "$src/static/js/components/wschat/saver.js;$bin/static/js/wschat/saver.js"
)

echo -en "\033]0;$TTL\a"

clear

check_dirs FF
check_dirs PP

copy_folder FF

while true;
do
    copira PP
    sleep 1
done

exit 0
